[package]
name = "spades"
version = "0.1.0"
authors = ["William <limwilliam23@gmail.com>"]
repository = "https://github.com/wlim33/rust-spades"
categories = ["games", "game-engines", "simulation"]
keywords = ["spades", "cards", "state", "machine"]
license = "MIT"
description = "A popular four person card game implemented in Rust."
[dependencies]
rand = "0.5"
uuid = { version = "0.6", features = ["v4"] }
